name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['2.6', '2.7', '3.0', '3.1', '3.2']
        mongoid-version: ['7.0']

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Update RubyGems and Bundler
      run: |
        gem update --system
        gem install bundler -v 2.4.22
    - name: Install dependencies
      run: |
        bundle _2.4.22_ install
    - name: Run tests
      run: bundle exec rspec
